### ISSUE TITLE
Make main script type module

### ISSUE THREAD

**Issue by folkertjan** [timruiterkamp/web-app-from-scratch-18-19#1]
changing this line to ` <script src="js/app.js" type="module"></script>` has the benefit that it automatically defers. This means you could put it in your head section so it loads a little bit faster.
[source](https://developers.google.com/web/fundamentals/primers/modules#defer)

https://github.com/timruiterkamp/web-app-from-scratch-18-19/blob/0bb2476276ff7f6fd891774e70cc609f0f204d95/src/index.html#L13

**Comment by Cavalon-io** [comment]
I use parcelJS for this, which probably better supports browsers in this. As <script type="module"> is relatively new, I can imagine this still lacks support on some browsers.

I used this before in other projects, but wanted to try out parcelJS for this project.

Thanks for the note!
