### ISSUE TITLE
Don't Capitalize function if not constructor / class

### ISSUE THREAD

**Issue by joostf** [timruiterkamp/web-app-from-scratch-18-19#10]
It's a convention to start constructor functions or classes with a capital cased letter, regular functions should start with a lowercased letter.

https://github.com/timruiterkamp/web-app-from-scratch-18-19/blob/a2cae7dc6bff67f590bcb93ce19dc983cb0b9798/src/js/router.js#L4

**Comment by Cavalon-io** [comment]
Used to be a class, but could be solved functionally. Forgot to change the name. Will do it right now. ;)

**Comment by Cavalon-io** [comment]
Fixed the naming!
