### ISSUE TITLE
Avoid using innerHTML

### ISSUE THREAD

**Issue by vandijkstef** [timruiterkamp/web-app-from-scratch-18-19#3]
Interesting approach to create the page, nice! However I'd suggest to avoid using innerHTML to create HTML.

https://github.com/timruiterkamp/web-app-from-scratch-18-19/blob/0bb2476276ff7f6fd891774e70cc609f0f204d95/src/js/data/getCompetition.js#L29

**Comment by Cavalon-io** [comment]
Changed the innerHTML to nodes.
