### ISSUE TITLE
Review the minification/compressing

### ISSUE THREAD

**Issue by vandijkstef** [timruiterkamp/web-app-from-scratch-18-19#5]
It looks like gatenkaas

**Comment by Cavalon-io** [comment]
Does this relate to the output of parcelJS?

**Comment by vandijkstef** [comment]
I was referring to [this output](https://web-app-from-scratch-tim.netlify.com/app.2d0e1e9e.js).
It seems compressed, not minified. Please make sure you are in control of parcelJS, and parcelJS isn't in control of you. This is a minor thing that caught my eye and actually more related to performance-matters.
