### ISSUE TITLE
Don't misuse operators as control statements

### ISSUE THREAD

**Issue by maanlamp** [timruiterkamp/web-app-from-scratch-18-19#7]
https://github.com/timruiterkamp/web-app-from-scratch-18-19/blob/cca25ddc5f25f7e270e98e7593b650100fcbdeb5/src/js/router.js#L36

Cool trick, but there should be an if/(else) somewhere. (Ternary) operators aren't for controlling flow.

**Comment by Cavalon-io** [comment]
You're right, changed it to if else statements
