### ISSUE TITLE
Use implicit return

### ISSUE THREAD

**Issue by maanlamp** [timruiterkamp/web-app-from-scratch-18-19#9]
https://github.com/timruiterkamp/web-app-from-scratch-18-19/blob/cca25ddc5f25f7e270e98e7593b650100fcbdeb5/src/js/data/getCompetition.js#L13-L25

Any reason for not just using the arrow function's implicit returns?

E.g.:
```js
.map(match => ` 
         <tr> 
         <td class="homeTeam"><a href="/team/${match.homeTeam.id}">${ 
           match.homeTeam.name 
         }</a></td> 
         <td class="awayTeam"> <a href="/team/${match.awayTeam.id}">${ 
           match.awayTeam.name 
         }</a></td> 
         <td class="playData"><time>${parseDate(match.utcDate)}</time></td> 
         </tr>`) 
       .join(""); 
```
Excuse the indentation.

**Comment by Cavalon-io** [comment]
I'm rebuilding this to nodes, so i will close this issue. You were right on the implicit return tho.
